"""split parcel order sender receiver

Revision ID: 0c5230776947
Revises: 5723142f41f5
Create Date: 2026-08-07 12:20:09.961030

FIX: Added op.create_table for parcel_senders and parcel_receivers which
were missing from the original autogenerated migration (tables existed on
the developer's local DB so Alembic skipped them).
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0c5230776947'
down_revision: Union[str, None] = '5723142f41f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create parcel_senders table (was missing from autogenerate)
    op.create_table('parcel_senders',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('mobile', sa.String(length=20), nullable=True),
        sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('address_line_1', sa.String(length=500), nullable=True),
        sa.Column('address_line_2', sa.String(length=500), nullable=True),
        sa.Column('pincode', sa.String(length=10), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('franchise_id', sa.String(length=36), nullable=True),
        sa.Column('warehouse_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_addresses.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_senders_created_by'), 'parcel_senders', ['created_by'], unique=False)
    op.create_index(op.f('ix_parcel_senders_franchise_id'), 'parcel_senders', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_parcel_senders_warehouse_id'), 'parcel_senders', ['warehouse_id'], unique=False)

    # 2. Create parcel_receivers table (was missing from autogenerate)
    op.create_table('parcel_receivers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('mobile', sa.String(length=20), nullable=True),
        sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('address_line_1', sa.String(length=500), nullable=True),
        sa.Column('address_line_2', sa.String(length=500), nullable=True),
        sa.Column('pincode', sa.String(length=10), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('franchise_id', sa.String(length=36), nullable=True),
        sa.Column('warehouse_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_addresses.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_receivers_created_by'), 'parcel_receivers', ['created_by'], unique=False)
    op.create_index(op.f('ix_parcel_receivers_franchise_id'), 'parcel_receivers', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_parcel_receivers_warehouse_id'), 'parcel_receivers', ['warehouse_id'], unique=False)

    # 3. Now add FK columns to parcel_orders pointing to the tables above
    op.add_column('parcel_orders', sa.Column('sender_id', sa.String(length=36), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_parcel_orders_receiver_id'), 'parcel_orders', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_parcel_orders_sender_id'), 'parcel_orders', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'parcel_orders', 'parcel_senders', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel_orders', 'parcel_receivers', ['receiver_id'], ['id'], ondelete='SET NULL')

    # 4. Drop old inline sender/receiver columns from parcel_orders
    op.drop_column('parcel_orders', 'receiver_mobile')
    op.drop_column('parcel_orders', 'sender_address_line_2')
    op.drop_column('parcel_orders', 'sender_lat')
    op.drop_column('parcel_orders', 'sender_alternate_mobile')
    op.drop_column('parcel_orders', 'sender_address_line_1')
    op.drop_column('parcel_orders', 'receiver_pincode')
    op.drop_column('parcel_orders', 'receiver_state')
    op.drop_column('parcel_orders', 'sender_name')
    op.drop_column('parcel_orders', 'sender_mobile')
    op.drop_column('parcel_orders', 'receiver_email')
    op.drop_column('parcel_orders', 'receiver_alternate_mobile')
    op.drop_column('parcel_orders', 'receiver_name')
    op.drop_column('parcel_orders', 'sender_email')
    op.drop_column('parcel_orders', 'receiver_city')
    op.drop_column('parcel_orders', 'receiver_address_line_1')
    op.drop_column('parcel_orders', 'sender_state')
    op.drop_column('parcel_orders', 'sender_city')
    op.drop_column('parcel_orders', 'receiver_address_line_2')
    op.drop_column('parcel_orders', 'sender_lng')
    op.drop_column('parcel_orders', 'sender_pincode')


def downgrade() -> None:
    # Re-add inline sender/receiver columns to parcel_orders
    op.add_column('parcel_orders', sa.Column('sender_pincode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_lng', mysql.FLOAT(), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_address_line_2', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_address_line_1', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_name', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_alternate_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_name', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_pincode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_address_line_1', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_alternate_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_lat', mysql.FLOAT(), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_address_line_2', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'parcel_orders', type_='foreignkey')
    op.drop_constraint(None, 'parcel_orders', type_='foreignkey')
    op.drop_index(op.f('ix_parcel_orders_sender_id'), table_name='parcel_orders')
    op.drop_index(op.f('ix_parcel_orders_receiver_id'), table_name='parcel_orders')
    op.drop_column('parcel_orders', 'receiver_id')
    op.drop_column('parcel_orders', 'sender_id')

    # Drop the parcel_receivers and parcel_senders tables
    op.drop_index(op.f('ix_parcel_receivers_warehouse_id'), table_name='parcel_receivers')
    op.drop_index(op.f('ix_parcel_receivers_franchise_id'), table_name='parcel_receivers')
    op.drop_index(op.f('ix_parcel_receivers_created_by'), table_name='parcel_receivers')
    op.drop_table('parcel_receivers')
    op.drop_index(op.f('ix_parcel_senders_warehouse_id'), table_name='parcel_senders')
    op.drop_index(op.f('ix_parcel_senders_franchise_id'), table_name='parcel_senders')
    op.drop_index(op.f('ix_parcel_senders_created_by'), table_name='parcel_senders')
    op.drop_table('parcel_senders')
