"""Add is_gst_exempt to orders

Revision ID: 10c2511d9e61
Revises: c739426df8e3
Create Date: 2026-06-27 15:35:44.444532

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '10c2511d9e61'
down_revision: Union[str, None] = 'c739426df8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.drop_index('ix_order_items_order_package_id', table_name='order_items')
    op.drop_column('order_items', 'order_package_id')
    op.add_column('orders', sa.Column('is_gst_exempt', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_gst_exempt')
    op.add_column('order_items', sa.Column('order_package_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'order_packages', ['order_package_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_order_items_order_package_id', 'order_items', ['order_package_id'], unique=False)
    # ### end Alembic commands ###
