"""add_country_remove_lat_lng_parcel_sender_receiver

Revision ID: 15fd41c6b185
Revises: 0c5230776947
Create Date: 2026-08-07 14:01:44.120587

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '15fd41c6b185'
down_revision: Union[str, None] = '0c5230776947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_receivers', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('parcel_senders', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_column('parcel_senders', 'lat')
    op.drop_column('parcel_senders', 'lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_senders', sa.Column('lng', mysql.FLOAT(), nullable=True))
    op.add_column('parcel_senders', sa.Column('lat', mysql.FLOAT(), nullable=True))
    op.drop_column('parcel_senders', 'country')
    op.drop_column('parcel_receivers', 'country')
    # ### end Alembic commands ###
