"""Revert regional_area back to float

Revision ID: 5c595aeeee89
Revises: 8166ac93b9a2
Create Date: 2026-06-26 12:46:58.174764

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

"""Revert regional_area back to float

Revision ID: 5c595aeeee89
Revises: 8166ac93b9a2
Create Date: 2026-06-26 12:46:58.174764

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '5c595aeeee89'
down_revision: Union[str, None] = '8166ac93b9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear any text values that can't be converted to float
    op.execute("UPDATE orders SET regional_area = NULL WHERE regional_area REGEXP '[^0-9.]'")
    op.alter_column('orders', 'regional_area',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'regional_area',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
