"""initial

Revision ID: 63c0d8b459d0
Revises: 
Create Date: 2026-06-23 18:33:57.653118

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '63c0d8b459d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
