"""initial

Revision ID: 63c0d8b459d0
Revises: 
Create Date: 2026-06-23 18:33:57.653118

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '63c0d8b459d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('orders')]
    
    if 'insurance' not in columns:
        op.add_column(
            'orders',
            sa.Column('insurance', sa.Float(), nullable=True)
        )
    if 'regional_area' not in columns:
        op.add_column(
            'orders',
            sa.Column('regional_area', sa.String(length=100), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('orders')]
    
    if 'regional_area' in columns:
        op.drop_column('orders', 'regional_area')
    if 'insurance' in columns:
        op.drop_column('orders', 'insurance')
    # ### end Alembic commands ###
