"""initial

Revision ID: 6a92181b8846
Revises: 
Create Date: 2026-06-23 21:09:56.899311

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6a92181b8846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchise_applications_byuser',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('current_address', sa.String(length=500), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('proposed_location', sa.String(length=255), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True),
    sa.Column('detailed_business_address', sa.String(length=500), nullable=True),
    sa.Column('prior_experience', sa.String(length=500), nullable=True),
    sa.Column('years_active', sa.Integer(), nullable=True),
    sa.Column('office_space_sqft', sa.Integer(), nullable=True),
    sa.Column('office_ownership', sa.String(length=20), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('internet_availability', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('computer_laptop', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('investment_capacity', sa.String(length=100), nullable=True),
    sa.Column('source_of_funds', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('existing_loans', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('existing_loan_details', sa.String(length=1000), nullable=True),
    sa.Column('preferred_service_area', sa.String(length=255), nullable=True),
    sa.Column('nearby_landmark', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('aadhar_file_path', sa.String(length=500), nullable=True),
    sa.Column('pan_file_path', sa.String(length=500), nullable=True),
    sa.Column('photo_file_path', sa.String(length=500), nullable=True),
    sa.Column('business_registration_file_path', sa.String(length=500), nullable=True),
    sa.Column('bank_statement_file_path', sa.String(length=500), nullable=True),
    sa.Column('doc_id_proof', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_address_proof', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_photographs', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_business_registration', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_bank_statement', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('agree_to_terms', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('submission_place', sa.String(length=255), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_franchise_applications_byuser_email'), 'franchise_applications_byuser', ['email'], unique=False)
    op.create_index(op.f('ix_franchise_applications_byuser_pincode'), 'franchise_applications_byuser', ['pincode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_franchise_applications_byuser_pincode'), table_name='franchise_applications_byuser')
    op.drop_index(op.f('ix_franchise_applications_byuser_email'), table_name='franchise_applications_byuser')
    op.drop_table('franchise_applications_byuser')
    # ### end Alembic commands ###
