"""Drop wallet tables

Revision ID: 7c17bdd33c02
Revises: ad220b622e6e
Create Date: 2026-06-26 14:57:49.540396

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '7c17bdd33c02'
down_revision: Union[str, None] = 'ad220b622e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wallet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('opening_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='wallet_transactions_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='wallet_transactions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_wallet_transactions_wallet_id', 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index('ix_wallet_transactions_order_id', 'wallet_transactions', ['order_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('franchise_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=14, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name='wallets_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_wallets_franchise_id', 'wallets', ['franchise_id'], unique=True)
    # ### end Alembic commands ###
