"""Change regional_area from float to string

Revision ID: 8166ac93b9a2
Revises: dfebfaee7342
Create Date: 2026-06-26 12:33:17.174835

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8166ac93b9a2'
down_revision: Union[str, None] = 'dfebfaee7342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
