"""Add RateMaster and detailed freight fields

Revision ID: ad220b622e6e
Revises: 5c595aeeee89
Create Date: 2026-06-26 14:37:01.541519

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ad220b622e6e'
down_revision: Union[str, None] = '5c595aeeee89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('weight_up_to', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_master_service_type'), 'rate_master', ['service_type'], unique=False)
    op.create_index(op.f('ix_rate_master_zone'), 'rate_master', ['zone'], unique=False)
    op.add_column('invoice_orders', sa.Column('freight_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('invoice_orders', sa.Column('freight_gst', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('invoice_orders', sa.Column('total_freight', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.drop_column('invoice_orders', 'shipping_charge')
    op.add_column('invoices', sa.Column('total_product_value', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('service_type', sa.String(length=20), server_default=sa.text("'Surface'"), nullable=False))
    op.add_column('orders', sa.Column('freight_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('freight_gst', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('total_freight', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('applied_weight_slab', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('pricing_zone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('is_manual_freight', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('manual_freight_reason', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'shipping_charge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_charge', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    op.drop_column('orders', 'manual_freight_reason')
    op.drop_column('orders', 'is_manual_freight')
    op.drop_column('orders', 'pricing_zone')
    op.drop_column('orders', 'applied_weight_slab')
    op.drop_column('orders', 'total_freight')
    op.drop_column('orders', 'freight_gst')
    op.drop_column('orders', 'freight_charge')
    op.drop_column('orders', 'service_type')
    op.drop_column('invoices', 'total_product_value')
    op.add_column('invoice_orders', sa.Column('shipping_charge', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    op.drop_column('invoice_orders', 'total_freight')
    op.drop_column('invoice_orders', 'freight_gst')
    op.drop_column('invoice_orders', 'freight_charge')
    op.drop_index(op.f('ix_rate_master_zone'), table_name='rate_master')
    op.drop_index(op.f('ix_rate_master_service_type'), table_name='rate_master')
    op.drop_table('rate_master')
    # ### end Alembic commands ###
