"""add invoicenumber and amount to orders

Revision ID: df10f274a2b9
Revises: 09dec204a975
Create Date: 2026-06-30 10:10:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'df10f274a2b9'
down_revision: Union[str, None] = '09dec204a975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoicenumber', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'invoicenumber')
    # ### end Alembic commands ###
