"""Add order_package_id to order_items

Revision ID: dfebfaee7342
Revises: 7b951c8a14b3
Create Date: 2026-06-26 11:42:08.027800

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dfebfaee7342'
down_revision: Union[str, None] = '7b951c8a14b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_package_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_order_items_order_package_id'), 'order_items', ['order_package_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'order_packages', ['order_package_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_order_package_id'), table_name='order_items')
    op.drop_column('order_items', 'order_package_id')
    # ### end Alembic commands ###
