"""Add razorpay QR fields to order

Revision ID: eaaec2cef7b3
Revises: 15fd41c6b185
Create Date: 2026-08-09 00:27:02.905083

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eaaec2cef7b3'
down_revision: Union[str, None] = '15fd41c6b185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_qr_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('razorpay_qr_url', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('razorpay_qr_upi_uri', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_qr_upi_uri')
    op.drop_column('orders', 'razorpay_qr_url')
    op.drop_column('orders', 'razorpay_qr_id')
    # ### end Alembic commands ###
