name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 15.207.220.194
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Roadoz-Courier-Backend
            git pull origin staging
            source venv/bin/activate
            pip install -r requirements.txt -q
            sudo systemctl restart roadoz
            sudo systemctl is-active roadoz

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 52.66.93.248
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Roadoz-Courier-Backend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt -q
            sudo systemctl restart roadoz
            sudo systemctl is-active roadoz
